### Numpy : Creation and manipulation

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5])
print(array1)
print(type(array1))
print(array1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
array2 = np.array([1,2,3,4,5])
array2.reshape(1,5) # 1 row and 5 column
print(array2.shape)

(5,)


In [4]:
array3 = np.array([[1,2,3,4,5], [6,7,8,9,0]])
print(array3)
print(array3.shape)

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)


In [5]:
array4 = np.arange(0,10,2).reshape(5,1)
print(array4)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [6]:
array5 = np.ones((6,6))
print(array5)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [7]:
array6 = np.eye(3)
print(array6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
array7 = np.array([[1,2,3], [4,5,6]])

print(f"Array: {array7}")
print(f"Shape: {array7.shape}")
print(f"Number of dimensions: {array7.ndim}")
print(f"Size (no. of elements): {array7.size}")
print(f"Data type: {array7.dtype}")
print(f"Item sizes (in bytes): {array7.itemsize}")

Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (no. of elements): 6
Data type: int64
Item sizes (in bytes): 8


### Numpy vectorised operations

In [9]:
array8 = np.array([1,2,3,4,5])
array9 = np.array([6,7,8,9,10])

# Element wise Addition
print(f"Addition: {array8 + array9}")

# Element wise subtraction
print(f"Subtraction: {array9 - array8}")

# Element wise Multiplication
print(f"Multiplication: {array9 * array8}")

# Element wise Division
print(f"Division: {array8 / array9}")

Addition: [ 7  9 11 13 15]
Subtraction: [5 5 5 5 5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [10]:
# Universal functions
array10 = np.array([1,2,3,4,5])

# Square root
print(f"Sqaure root: {np.sqrt(array10).reshape(5,1)}")

# Exponential
print(f"Exponential: {np.exp(array10).reshape(5,1)}")

# Sin func
print(f"Sin function: {np.sin(array10).reshape(5,1)}")

# Log function
print(f"Log function: {np.log(array10).reshape(5,1)}")

Sqaure root: [[1.        ]
 [1.41421356]
 [1.73205081]
 [2.        ]
 [2.23606798]]
Exponential: [[  2.71828183]
 [  7.3890561 ]
 [ 20.08553692]
 [ 54.59815003]
 [148.4131591 ]]
Sin function: [[ 0.84147098]
 [ 0.90929743]
 [ 0.14112001]
 [-0.7568025 ]
 [-0.95892427]]
Log function: [[0.        ]
 [0.69314718]
 [1.09861229]
 [1.38629436]
 [1.60943791]]


In [11]:
# Slicing and Indexing
array11 = np.array([[1,2,3,4], [11,22,33,44], [111,222,333,444]])
print(f"Array: {array11}") 

Array: [[  1   2   3   4]
 [ 11  22  33  44]
 [111 222 333 444]]


In [12]:
print(f"{array11[1:3,1:3]}")

[[ 22  33]
 [222 333]]


In [13]:
print(f"{array11[0:2, 0:2]}")

[[ 1  2]
 [11 22]]


### Statistical concept - Normalization to have a mean of 0 and standard deviation of 1

In [14]:
# Normalization 
array12 = np.array([11,22,33,44,55])
mean = np.mean(array12)
std_dev = np.std(array12)

normalized_array12 = (array12 - mean) / std_dev
print(f"Normalized array: {normalized_array12}")

Normalized array: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [16]:
array13 = np.array([12,13,14,15,16])

# Mean
print(f"Mean; {np.mean(array13)}")

# Median
print(f"Median: {np.median(array13)}")

# Standard deviation
print(f"Standard deviation; {np.std(array13)}")

# Variance
print(f"Variance: {np.var(array13)}")

Mean; 14.0
Median: 14.0
Standard deviation; 1.4142135623730951
Variance: 2.0


In [18]:
# Logical operations
array14 = np.array([1,2,3,4,5,6])
array14[array14>3]

array([4, 5, 6])